### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by mbwgh** [T-Systems-MMS/check_springboot_actuator#9]
Python2 has reached end of life by now, and starting next year, pip will officially [drop support](https://pip.pypa.io/en/stable/development/release-process/#python-2-support).

As far as I understood, you can still fetch dependencies using a legacy resolver then, but of course this is less than ideal.
Are there any plans for a Python3 port?

**Comment by jandd** [comment]
`python3 check_springboot_actuator.py` should work. We have a `#!/usr/bin/env python` shebang line at the beginning of the script to be compatible with the default Python installation on RHEL/CentOS 7 systems but tried to be compatible with Python 3.
The pynag version specified in requirements.txt seems to be incompatible with Python 3 though.
`python3 -m pip install -r requirements.txt` fails because pynag 0.9.1 uses old print syntax. Installing a recent pynag and requests version seems to help:

```
$ python3 -m pip install pynag
Collecting pynag
  Downloading pynag-1.1.2.tar.gz (228 kB)
     |████████████████████████████████| 228 kB 3.0 MB/s 
Collecting chardet
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Using legacy setup.py install for pynag, since package 'wheel' is not installed.
Installing collected packages: chardet, six, pynag
    Running setup.py install for pynag ... done
Successfully installed chardet-3.0.4 pynag-1.1.2 six-1.15.0

$ python3 -m pip install requests
Collecting requests
  Using cached requests-2.25.0-py2.py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.venv/lib/python3.8/site-packages (from requests) (3.0.4)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 3.0 MB/s 
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Installing collected packages: urllib3, certifi, idna, requests
Successfully installed certifi-2020.12.5 idna-2.10 requests-2.25.0 urllib3-1.26.2
```

`python3 check_springboot_actuator.py`

should work with current dependencies.
